name: TonTeeTon Contract Verification
run-name: Verify get-simple-price - ${{ github.event.inputs.CONTRACT_ADDRESS }}
on:
  workflow_dispatch:
    inputs:
      CONTRACT_ADDRESS:
        description: 'TON contract address to verify'
        required: true
        default: ''
      EXPECTED_MEASUREMENT:
        description: 'Expected Enclave measurement (MRENCLAVE)'
        required: true
        default: ''

jobs:
  verify-contract:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Contract
        run: |
          ADDRESS="${{ github.event.inputs.CONTRACT_ADDRESS }}"
          MEASUREMENT="${{ github.event.inputs.EXPECTED_MEASUREMENT }}"

          set -o pipefail
          {
            echo "### Verifying Contract"
            echo "- **Contract Address:** [$ADDRESS](https://tonscan.org/address/$ADDRESS)"
            echo "- **Expected Measurement:** $MEASUREMENT"
            echo ""

            docker run --rm --quiet \
              ghcr.io/tonteeton/verifier:latest \
              "$ADDRESS" \
              "$MEASUREMENT" 2>&1
            VERIFICATION_STATUS=$?

            if [ $VERIFICATION_STATUS -ne 0 ]; then
                echo "❌ Contract attestation report was not verified"
                exit 1
            fi            
          } | tee -a "$GITHUB_STEP_SUMMARY"
